module.exports = {
  NO_DATA: 'ERR_NO_DATA',
  LOGIN_FAIL: 'LOGIN_FAIL',
  ECONNREFUSED: 'ECONNREFUSED',
  REGISTERED_FAILED: 'REGISTERED_FAILED',
  SEND_CODE_FAILED: 'SEND_CODE_FAILED',
  VERIFY_FAILED: 'VERIFY_FAILED',
  ACTIVATE_FAILED: 'ACTIVATE_FAILED',
};
